---
title: ""
format:
  html:
    toc: true
    toc-depth: 3
    embed-resources: true
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, dpi = 600, fig.width = 8)

library(adcp)
library(dplyr)
library(DT)
library(ggplot2)
library(here)
library(lubridate)
library(plotly)
library(readr)
library(waves)
library(tidyr)

theme_set(theme_light())

dt_options <- list(
  dom = 'ft',
  paging = FALSE,
  searching = FALSE,
  scrollY = "500px",
  columnDefs = list(list(className = 'dt-center', targets = "_all"))
)

theme_facet_plotly <- theme(
  panel.spacing.y = unit(15, "lines"),
  panel.spacing.x = unit(15, "lines")
)

path <- here("data-raw")

```

`r Sys.Date()`

# Angus Shoal

```{r}
#| message: false

file_name <- "2022.09.29 - Angus Shoal - Waves.txt"

wave1 <- wv_read_txt(path, file_name = file_name) %>% 
  mutate(timestamp_utc = round_date(timestamp_utc, unit = "minute"))

current1 <- read_csv(
  here("data-raw/2022-09-29_Angus Shoal_YR008.csv"), show_col_types = FALSE
) %>% 
  mutate(timestamp_utc = round_date(timestamp_utc, unit = "minute"))

avg_bins1 <- current1 %>% 
  group_by(timestamp_utc, bin_height_above_sea_floor_m) %>%
  summarise(
    speed_m_s = mean(sea_water_speed_m_s),
    to_direction_degree = mean(sea_water_to_direction_degree),
    sensor_depth_m = mean(sensor_depth_below_surface_m)
  ) %>% 
  ungroup() %>% 
  right_join(wave1, by = join_by(timestamp_utc))

avg1 <- current1 %>% 
  group_by(timestamp_utc) %>% 
  summarise(
    speed_m_s = mean(sea_water_speed_m_s),
    to_direction_degree = mean(sea_water_to_direction_degree),
    sensor_depth_m = mean(sensor_depth_below_surface_m)
  ) %>% 
  ungroup() %>% 
  right_join(wave1, by = join_by(timestamp_utc)) %>% 
  mutate(bin_height_above_sea_floor_m = 100) 

comp1 <- avg1 %>% 
  bind_rows(avg_bins1) %>% 
  select(
    timestamp_utc, 
    bin_height_above_sea_floor_m,
    speed_m_s, to_direction_degree, CM, CD,
    sensor_depth_m, Depth 
  ) 

```

::: panel-tabset

### Figure 1
```{r}
#| message: false
#| fig-height: 20

comp1 %>% 
  pivot_longer(
    cols = c("speed_m_s", "CM"), names_to = "variable", 
    values_to = "speed_m_s"
  ) %>% 
  ggplot(aes(timestamp_utc, speed_m_s, col = variable)) +
  geom_point() +
  facet_wrap(~bin_height_above_sea_floor_m, ncol = 1)
```

### Figure 2
```{r}
#| fig-height: 20

ggplot(comp1, aes(speed_m_s, CM)) +
  geom_point() +
  facet_wrap(~bin_height_above_sea_floor_m, ncol = 1)
```

:::

### Figure 3
```{r}
#| message: false
#| fig-height: 20

comp1 %>% 
  pivot_longer(
    cols = c("to_direction_degree", "CD"), names_to = "variable", 
    values_to = "to_direction_degree"
  ) %>% 
  ggplot(aes(timestamp_utc, to_direction_degree, col = variable)) +
  geom_point() +
  facet_wrap(~bin_height_above_sea_floor_m, ncol = 1)
```

::: panel-tabset

### Figure 4
```{r}
comp1 %>% 
  pivot_longer(
    cols = contains("epth"), 
    values_to = "depth_m", names_to = "variable") %>% 
  ggplot(aes(timestamp_utc, depth_m, col = variable)) +
  geom_point() 
```

### Figure 5
```{r}
ggplot(comp1, aes(Depth, sensor_depth_m)) +
  geom_point()
```

:::

### Table 1
```{r}
#| message: false
mse1 <- comp1 %>% 
  group_by(bin_height_above_sea_floor_m) %>% 
  mutate(
    cm_se = (speed_m_s - CM)^2,
    cd_se = (to_direction_degree - CD)^2,
    depth_se = (sensor_depth_m - Depth)^2
  ) %>% 
  summarise(
    cm_mse = mean(cm_se), 
    cd_mse = mean(cd_se),
    depth_mse = mean(depth_se)
    ) %>% 
  ungroup() %>% 
  mutate(
    cm_mse = round(cm_mse, digits = 5), 
    cd_mse = round(cd_mse),
    depth_mse = round(depth_mse, digits = 5)
  ) %>% 
  arrange(cm_mse)

mse1 %>% 
  datatable(options = dt_options, rownames = FALSE)
```

# Western Shoal

```{r}
file_name2 <- "2022.09.29 - Western Shoal - Waves.txt"

wave2 <- wv_read_txt(path, file_name = file_name2) %>% 
  mutate(timestamp_utc = round_date(timestamp_utc, unit = "minute"))

current2 <- read_csv(
  here("data-raw/2022-09-29_Western Shoal_YR009.csv"), show_col_types = FALSE
) %>% 
  mutate(timestamp_utc = round_date(timestamp_utc, unit = "minute"))

avg_bins2 <- current2 %>% 
  group_by(timestamp_utc, bin_height_above_sea_floor_m) %>% 
  summarise(
    speed_m_s = mean(sea_water_speed_m_s),
    to_direction_degree = mean(sea_water_to_direction_degree),
    sensor_depth_m = mean(sensor_depth_below_surface_m)
  ) %>% 
  ungroup() %>% 
  right_join(wave2, by = join_by(timestamp_utc))

avg2 <- current2 %>% 
  group_by(timestamp_utc) %>% 
  summarise(
    speed_m_s = mean(sea_water_speed_m_s),
    to_direction_degree = mean(sea_water_to_direction_degree),
    sensor_depth_m = mean(sensor_depth_below_surface_m)
  ) %>% 
  ungroup() %>% 
  right_join(wave2, by = join_by(timestamp_utc)) %>% 
  mutate(bin_height_above_sea_floor_m = 100) 

comp2 <- avg2 %>% 
  bind_rows(avg_bins2) %>% 
  select(
    timestamp_utc, 
    bin_height_above_sea_floor_m,
    speed_m_s, to_direction_degree, CM, CD,
    sensor_depth_m, Depth
  ) 

```

::: panel-tabset

### Figure 6
```{r}
#| fig-height: 20

comp2 %>% 
  pivot_longer(
    cols = c("speed_m_s", "CM"), names_to = "variable", 
    values_to = "speed_m_s"
  ) %>% 
  ggplot(aes(timestamp_utc, speed_m_s, col = variable)) +
  geom_point() +
  facet_wrap(~bin_height_above_sea_floor_m, ncol = 1)
```

### Figure 7
```{r}
#| fig-height: 20

ggplot(comp2, aes(speed_m_s, CM)) +
  geom_point() +
  facet_wrap(~bin_height_above_sea_floor_m, ncol = 1)
```
:::

### Figure 8
```{r}
#| fig-height: 20

comp2 %>% 
  pivot_longer(
    cols = c("to_direction_degree", "CD"), names_to = "variable", 
    values_to = "to_direction_degree"
  ) %>% 
  ggplot(aes(timestamp_utc, to_direction_degree, col = variable)) +
  geom_point() +
  facet_wrap(~bin_height_above_sea_floor_m, ncol = 1)
```

::: panel-tabset
### Figure 9

```{r}
comp2 %>% 
  pivot_longer(
    cols = contains("epth"), 
    values_to = "depth_m", names_to = "variable") %>% 
  ggplot(aes(timestamp_utc, depth_m, col = variable)) +
  geom_point() 
```

### Figure 10
```{r}
ggplot(comp2, aes(Depth, sensor_depth_m)) +
  geom_point()
```
:::

### Table 2

```{r}

mse2 <- comp2 %>% 
  group_by(bin_height_above_sea_floor_m) %>% 
  mutate(
    cm_se = (speed_m_s - CM)^2,
    cd_se = (to_direction_degree - CD)^2,
    depth_se = (sensor_depth_m - Depth)^2
  ) %>% 
  summarise(
    cm_mse = mean(cm_se, na.rm = TRUE), 
    cd_mse = mean(cd_se, na.rm = TRUE),
    depth_mse = mean(depth_se, na.rm = TRUE)
  ) %>% 
  ungroup() %>% 
  mutate(
    cm_mse = round(cm_mse, digits = 5), 
    cd_mse = round(cd_mse),
    depth_mse = round(depth_mse, digits = 5)
  ) %>% 
  arrange(cm_mse)

mse2 %>% 
  datatable(options = dt_options, rownames = FALSE)
```

