---
title: ""
format:
  html:
    toc: true
    toc-depth: 3
    embed-resources: true
editor_options: 
  chunk_output_type: console
---


```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, dpi = 600, fig.width = 8)

library(adcp)
library(dplyr)
library(DT)
library(ggplot2)
library(here)
library(plotly)
library(readr)
library(waves)
library(tidyr)

theme_set(theme_light())

dt_options <- list(
  dom = 'ft',
  paging = FALSE,
  searching = FALSE,
  scrollY = "500px",
  columnDefs = list(list(className = 'dt-center', targets = "_all"))
)

theme_facet_plotly <- theme(
  panel.spacing.y = unit(15, "lines"),
  panel.spacing.x = unit(15, "lines")
)

nsdfa <- adcp_read_nsdfa_metadata(here("data-raw/2023-11-27 - NSDFA Tracking Sheet.xlsx")) %>% 
  filter(Station_Name == "Angus Shoal") %>% 
  wv_write_report_table()

path <- here("data-raw")
file_name <- "2022.09.29 - Angus Shoal - Waves.txt"
```

# Angus Shoal Wave Parameters

`r Sys.Date()`

## Deployment Details

```{r}
nsdfa %>% 
  t() %>% 
  datatable(options = dt_options, colnames = " ")
```

## Data

### Data File
```{r, echo=TRUE}

dat <- wv_read_txt(path, file_name = file_name)

head(dat)
```

### Variable Descriptions
```{r}
read_csv(here("dev/wave_variables.csv"), show_col_types = FALSE) %>% 
  select(Variable, Unit, Description) %>% 
  na.omit() %>% 
  datatable(options = dt_options, rownames = FALSE)
```

## Figures

```{r}
#| fig-height: 10
#| fig-cap: Time series of each parameter in the wave data.

levels <- c(
  "Hs", "Tp", "Dp", 
  "H1/3", "T1/3", "CD",     
  "H1/10", "T1/10", "CM",
  "Hmax", "Tmax", "Depth"
)

dat_long <- dat %>%
  pivot_longer(
    cols = Hs:CD, names_to = "variable", values_to = "value"
  ) %>% 
  mutate(variable = ordered(variable, levels = levels))

p <- ggplot(dat_long, aes(timestamp_utc, value)) +
  geom_point(col = "grey20") +
  facet_wrap(~variable, ncol = 3, scales = "free_y") +
  theme_facet_plotly

ggplotly(p)

```

### Wave Height

```{r}
#| fig-height: 6
#| fig-cap: Time series of wave height parameters (filtered out 0's).

h <- dat %>%
  select(timestamp_utc, Hs, `H1/10`, `H1/3`, Hmax) %>%
  pivot_longer(cols = Hs:Hmax, names_to = "variable", values_to = "value")

p <- h %>%
  filter(value != 0) %>%
  ggplot(aes(timestamp_utc, value, col = variable, group = variable)) +
  geom_line(linewidth = 1) 

ggplotly(p)

```

### Wave Period

::: panel-tabset

### Filtered
```{r}
#| fig-height: 6
#| fig-cap: Time series of frequency (filtered out negative frequencies).

per <- dat %>%
  select(timestamp_utc, Tp, `T1/10`, `T1/3`, Tmax) %>%
  pivot_longer(
    cols = Tp:Tmax, names_to = "variable", values_to = "value"
  )

p <- per %>%
  filter(value > 0) %>%
  ggplot(aes(timestamp_utc, value, col = variable, group = variable)) +
  geom_line(linewidth = 1) 

ggplotly(p)
```

### All
```{r}
#| fig-height: 6
#| fig-cap: Time series of frequency (filtered out negative frequencies).

per <- dat %>%
  select(timestamp_utc, Tp, `T1/10`, `T1/3`, Tmax) %>%
  pivot_longer(
    cols = Tp:Tmax, names_to = "variable", values_to = "value"
  )

p <- per %>%
  ggplot(aes(timestamp_utc, value, col = variable, group = variable)) +
  geom_point() 

ggplotly(p)
```

::: 

### Current 
```{r}

ggplot(dat, aes(Dp, CD, col = Tp)) +
  geom_point(alpha = 0.8)

```


## Conclusions

- Zero values in wave height period values from zero-crossing analysis should be considered `NULL` values.
- Current direction (CD) is not the same as the wave direction at the peak period (Tp).




